In [3]:
import numpy as np

# Basics

In [4]:
# we can declare a numpy array
a = np.array([1, 2, 3, 4, 5]) 
a


array([1, 2, 3, 4, 5])

In [5]:
# we can declare a numpy array
a = np.array([1, 2, 3, 4, 5]) 
print(a)


[1 2 3 4 5]


In [6]:
b= np.array([[6, 7, 8, 9, 10],[11, 12, 13, 14, 15]])
# here we made a 2D array where we have shape(2,5) , in math this is a matrix with 2 rows and 5 columns
print(b)
# look, In NumPy, a “matrix” is just a special case of an ndarray with 2 dimensions.

[[ 6  7  8  9 10]
 [11 12 13 14 15]]


In [7]:
# to get the dimensions of the array
b.ndim

2

In [8]:
# to get the shape of the array
b.shape
# it tells you the number of rows and columns in the array
# in this case, it is (2, 5) which means 2 rows and 5 columns

(2, 5)

In [9]:
 # to get the data type of the array
f = np.array([1.5, 2.5, 3.5, 4.5, 5.5])
print(a.dtype)
print(f.dtype)
# it tells you the data type of the elements in the array
# in this case, it is int64 which means the elements are 64-bit integers

int64
float64


In [10]:
#if do you eant to have a specific data type, you can specify it when creating the array
g = np.array([1, 2, 3, 4, 5], dtype=np.float32)
print(g.dtype)
g
# here we specified the data type as float32, which means the elements are 32-bit floating-point numbers

float32


array([1., 2., 3., 4., 5.], dtype=float32)

In [11]:
# also when we are not taking large numbers, we can use int8, int16, int32, int64
# and for floating point numbers, we can use float16, float32, float64
# these are the most common data types used in NumPy arrays

c= np.array([1, 2, 3, 4, 5], dtype=np.int16)
print(c.dtype)
# here we specified the data type as int8, which means the elements are 8-bit integers
# this is useful when we want to save memory and we know that the values will not exceed the range of int8

int16


In [12]:
# get size of the array
print(c.size)
# it tells you the number of elements in the array
# in this case, it is 5 which means there are 5 elements in the array

# is we want to get the size of the array in bytes
c.itemsize
# it tells you the size of each element in the array in bytes
# in this case, it is 1 which means each element is 2 byte

# to get whole size of the array in bytes
c.nbytes # equal to c.size * c.itemsize
# it tells you the total size of the array in bytes
# in this case, it is 10 which means the array takes 10 bytes of memory

5


10

In [13]:
# to be clear 

#numpy arrays are homogeneous, meaning all elements must be of the same data type.
# so for example, you cannot have a numpy array with both integers and strings.

s = np.array([1, 2, 3, 4.5 , 5])
# this will create an array with all elements as strings, because numpy will convert the integers to float to make them homogeneous
print(s)
# it will print ['1' '2' '3' '4' '5'] which means all elements are strings

x= np.array([1, 2, 3, 4.5 , '5'])
print(x)


[1.  2.  3.  4.5 5. ]
['1' '2' '3' '4.5' '5']


In [14]:
#we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray
mo=[1, 2, 3, 4.5 , '5']
a1= np.array(mo)
print(a1)
# it will print [1 2 3 4.5 '5'] which means all elements are strings

['1' '2' '3' '4.5' '5']


# Accessing/Changing specific elemts , row , colums ,etc

In [15]:
a = np.array([[1, 2, 3, 4, 5] ,[6, 7, 8, 9, 10]])
print(a)
a.shape

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


(2, 5)

In [16]:
# get specific element , we are using indexing (row, column)
print(a[0, 0])
# we can use negative indexing to get the last element
print(a[0, -1])



1
5


In [17]:
# get specific row

a[0]

array([1, 2, 3, 4, 5])

In [18]:
 # to get specific column, we can use slicing
print(a[:, 1])

[2 7]


In [19]:
# to get more fancy [startinging, ending, step] , it is like i want to get betwwen 2 and 6 but 

a[0,1 : 6:2]

#[in row,starting, ending, step]
# this will give us the elements in the first row starting from index 1 to index 6 with a step of 2
# so it will give us [2, 4]
# we can also use negative indexing to get the last element
# for example, a[0, -1] will give us the last element in the first row

array([2, 4])

In [20]:
# we change using index too 

a[1,0]= 100
print(a)
# this will change the element in the second row and first column to 100
# so the array will be [[1, 2, 3, 4, 5], [100, 7, 8, 9, 10]]

# we can do the same for series of numbers

a[:,2] = 20

a

[[  1   2   3   4   5]
 [100   7   8   9  10]]


array([[  1,   2,  20,   4,   5],
       [100,   7,  20,   9,  10]])

In [21]:
# 3D example 

d= np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [22]:
# to have a specific element in a 3D array, we can use indexing like this
print(d[0, 1, 0])  # This will give us the element at the first block, second row, first column
# it will print 3

# we are not deaing with matrices here, we are dealing with 3D shapes 
# so we can have 3D arrays with more than 2 dimensions

3


In [23]:
#replace 
d[:,1,:] = [[8, 9], [10, 11]]
print(d) 
# this will replace the second row of each block with the new values
# so the array will be [[[1, 2], [8, 9]], [[5, 6], [10, 11]]]
# you can not do shomething like this : d[:,1,:] = [[8, 9,10], [10, 11]] 
# it will raise an error because the shape of the array will not match
# so you have to make sure that the shape of the array matches the shape of the values you are trying to assign

[[[ 1  2]
  [ 8  9]]

 [[ 5  6]
  [10 11]]]


In [24]:
t= np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]] , [[1,2,3,4], [5,6,7,8]]])
t

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]]])

# initialize different types of arrays 

In [25]:
# all zeroes matrix
z= np.zeros((3, 4))  # 3 rows and 4 columns
# this will create a 2D array with 3 rows and 4 columns filled with zeros

print(z)

# toy can use in in all shapes, like 3D, 4D, etc.
l=np.zeros((2, 3, 4,5))  # 2 blocks, 3 rows and 4 columns
# this will create a 3D array with 2 blocks, each block has 3 rows and 4 columns filled with zeros

#Breaking down the shape (2, 3, 4, 5):
#1st dim = 2 → number of “big blocks” (think of it like 2 cubes)

#2nd dim = 3 → each block has 3 layers

#3rd dim = 4 → each layer has 4 rows

#4th dim = 5 → each row has 5 columns

#So the total number of elements = 2 × 3 × 4 × 5 = 120 zeros.

l

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [26]:
# all ones matrix
o= np.ones((3, 4))  # 3 rows and 4 columns
# this will create a 2D array with 3 rows and 4 columns filled with ones
print(o)

# you can also specify the data type when creating the array
o_float = np.ones((3, 4), dtype=np.int8)
o_float

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [27]:
# any other array can be created using the same method
# for example, you can create an array of random numbers, or an array of a specific value
# you can use np.full() to create an array filled with a specific value
full_array = np.full((2, 3), 7)  # 2 rows and 3 columns filled with 7
print(full_array)

[[7 7 7]
 [7 7 7]]


In [28]:
# fill_like 
# if i want to modify an existing array to have same num 
np.full(l.shape, 5)  # this will create an array with the same shape as l filled with 5
# so if l is a 3D array with shape (2, 3, 4, 5), it will create an array with the same shape filled with 5
# this is useful when you want to create an array with the same shape as another array but with different values
np.full_like(t, 5)


array([[[5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5]]])

In [29]:
# random decimal numbers
np.random.rand(2, 3)  # 2 rows and 3 columns filled with random numbers between 0 and 1
# this will create a 2D array with 2 rows and 3 columns filled with random numbers between 0 and 1
# you can also specify the data type when creating the array

np.random.random_sample(t.shape)

array([[[0.21988212, 0.21012009, 0.12974286, 0.79480223],
        [0.37959198, 0.91461495, 0.39207257, 0.93232593]],

       [[0.84734484, 0.02363474, 0.89931144, 0.96235288],
        [0.60344794, 0.13362412, 0.68829348, 0.93025742]],

       [[0.08459535, 0.67885452, 0.39002916, 0.73270762],
        [0.11036042, 0.13417752, 0.93054768, 0.56543055]]])

In [30]:
# random integers
np.random.randint(4,10, size=(2, 3)) # random nymbers between 4 and 10, with shape (2, 3)
# this will create a 2D array with 2 rows and 3 columns filled with random integers between 4 and 10
# you can also specify the data type when creating the array



array([[5, 5, 7],
       [5, 5, 4]], dtype=int32)

In [31]:
# we can also make identity matrix 
np.identity(3)  # 3x3 identity matrix
# this will create a 2D array with 3 rows and 3 columns filled with ones on the diagonal and zeros elsewhere
# it is useful in linear algebra and matrix operations
# you can also specify the data type when creating the array


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
# to repeat an array 
y=np.array([1, 2, 3])
# to repeat the array 3 times
np.repeat(t,3 , axis=1) 

array([[[ 1,  2,  3,  4],
        [ 1,  2,  3,  4],
        [ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 5,  6,  7,  8],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [ 9, 10, 11, 12],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [13, 14, 15, 16],
        [13, 14, 15, 16]],

       [[ 1,  2,  3,  4],
        [ 1,  2,  3,  4],
        [ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 5,  6,  7,  8],
        [ 5,  6,  7,  8]]])

In [33]:
mat= np.ones((5, 5))  
mat[1:4,1:4]=0
mat[2,2]=9

print(mat)


#Also 

out= np.ones((5, 5))  
z=np.zeros((3, 3))
z[1,1]=9
print(z)
out[1:4,1:4]=z
print(out)

print(mat==out)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


Beeee careful when copies an array!!!!!!!!!!!!!!!

In [34]:
a=np.array([1, 2, 3, 4, 5])
# Beeee careful when copies an array!!!!!!!!!!!!!!!
b=a
b[0]=100
print(a)

# that is becuase that two arrays are pointing to the same memory location
# so if you change one, the other will change too
# if you want to create a copy of the array, you can use the copy() method

b = a.copy()
b[0] = 200
print(a)
print(b)

[100   2   3   4   5]
[100   2   3   4   5]
[200   2   3   4   5]


# Mathematcial operations

- one of the big uses of NumPy is all the mathematical cabilities that it offer

In [35]:
a=np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [36]:
a+2


# we add 2 to all elements in the array
# it will return a new array with the same shape as the original array but with all elements increased by 2
# so it will return [3, 4, 5, 6, 7]

array([3, 4, 5, 6, 7])

In [37]:
print(a-2 )
# this will subtract 2 from all elements in the array
# look here that all those opwerations doesn't change the original array'ArithmeticError
print(a)

[-1  0  1  2  3]
[1 2 3 4 5]


In [38]:
print(a*2)
print(a/2)


[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]


In [39]:
#but when will you change the original array? when use assiment operators like +=, -=, *=, /=, etc.
a += 2
print(a)
# this will add 2 to all elements in the array and change the original array
# so it will return [3, 4, 5, 6, 7]

[3 4 5 6 7]


In [40]:
print(a)
print(a+2)
print(a)

[3 4 5 6 7]
[5 6 7 8 9]
[3 4 5 6 7]


In [41]:
# you can also 
b= np.array([1, 2, 3, 4, 5])
a+b

array([ 4,  6,  8, 10, 12])

In [42]:
a**2

array([ 9, 16, 25, 36, 49])

In [43]:
# take sin 
print (np.sin(a))
# this will take the sine of all elements in the array
# it will return a new array with the same shape as the original array but with all elements replaced by their sine values
# so it will return [0.14112001, 0.90929743, 0.14112001, -0.7568025 , -0.95892427]
print(a)

[ 0.14112001 -0.7568025  -0.95892427 -0.2794155   0.6569866 ]
[3 4 5 6 7]


# Linear Algebra stuff

In [44]:
# lets's say we have two matrices
a=np.ones((2, 3),dtype="int8")  # 2x2 matrix filled with ones

print(a)

b=np.full((3, 2), 2)  # 2x2 matrix filled with twos
print(b)

# a*b will not work because the shapes are not compatible

# but we can use : 
np.matmul(a,b)

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]


array([[6, 6],
       [6, 6]])

In [45]:
c=np.identity(3)
np.linalg.det(c) 
# this will calculate the determinant of the matrix c
# it will return 1.0 because the determinant of an identity matrix is always 1
# you can also use np.linalg.inv(c) to calculate the inverse of the matrix c
# it will return the same matrix because the inverse of an identity matrix is always the identity matrix

np.float64(1.0)

# Stat

In [46]:
a= np.array([[1, 2], [3, 4]])
print(np.min(a))
print(np.min(a, axis=0))  # minimum of each column
print(np.min(a, axis=1))  # minimum of each row

print(np.max(a, axis=0))  # minimum of each column
print(np.max(a, axis=1))  # minimum of each row
# this will return the minimum value of each column and each row respectively


1
[1 2]
[1 3]
[3 4]
[2 4]


In [47]:
np.max(a)

np.int64(4)

In [48]:
print(np.sum(a) ) # sum of all elements in the array)
print(np.sum(a, axis=0))  # sum of each column
print(np.sum(a, axis=1))  # sum of each row
# this will return the sum of all elements in the array, the sum of each column and the sum of each row respectively

10
[4 6]
[3 7]


# Reorganizing Arrays

In [55]:
before= np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(before.shape)

after= before.reshape(5,2)
print(after)
after= before.reshape(10,1)
print(after)        

# here we have 10 elements in the array, so we can reshape it to any shape that has 10 elements
# for example, we can reshape it to (5, 2) or (10, 1) or (2, 5) or (1, 10)
# but we cannot reshape it to (3, 4) because it has 12 elements and the original array has only 10 elements
# so the shape must be compatible with the number of elements in the array



(2, 5)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


# Vertically Stacking Vectors

In [62]:
v1= np.array([1, 2, 3])
v2= np.array([4, 5, 6])

np.vstack((v1, v2,v1,v2))
# this will stack the two vectors vertically, creating a 2D array with 2 rows and 3 columns
# so it will return [[1, 2, 3], [4, 5, 6]]


# note vectors mus t have the same number of elements to be stacked vertically
# if they have different number of elements, it will raise an error
# for example, if we try to stack v1 and v2 with different number of elements, it will raise an error
# so we have to make sure that the vectors have the same number of elements before stacking them vertically


array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

- why Iportant?? 


Why it’s important:
Turning several 1D arrays into a table

If you have multiple result vectors (like measurements from different experiments), vstack turns them into rows in a single 2D dataset.

Batching data

In ML or image processing, each sample might be a vector. You can stack samples into a matrix for training.

Merging results from loops

If you generate arrays in a loop, vstack lets you combine them easily without manually reshaping.



In [63]:
# horizontally stacking vectors
np.hstack((v1, v2))
# this will stack the two vectors horizontally, creating a 1D array with 6 elements
# so it will return [1, 2, 3, 4, 5, 6]

array([1, 2, 3, 4, 5, 6])

# Miscellaneous 

load data from files 


-  if you have some sort of data like txt and you don't want to use pandas but you want to loud all data from txt inro np array 

In [66]:
file= np.genfromtxt('data.txt', delimiter=',',dtype="int16")  # load data from a text file with comma as delimiter
print(file)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


# advanced indixing

- boolean masking and advanced indexing

In [70]:
file>50

# we can index file with a boolean mask
# this will return a new array with the same shape as the original array but with only the elements that are greater than 50
# so it will return an array with all elements that are greater than 50
file[file > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int16)

In [73]:
# you can index with list in numpy
a= np.array([1,2,3,4,5, 6,7,8,9,10])
a[[1,5,2,8]]

array([2, 6, 3, 9])

In [74]:
# we want to know if any num in volumn in file is greater than 50
np.any(file >50 , axis = 0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [75]:
# we can aslo check is all column is greater than 50
np.all(file >50 , axis = 0)
# this will return True if all elements in the column are greater than 50, otherwise it will return False

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [99]:
# we can have also multiple conditions
np.all(file >50 , axis = 0) & np.any(file < 100, axis = 0)
# this will return True if all elements in the column are greater than 50 and any element in the column is less than 100, otherwise it will return False
# you can use any combination of conditions using & (and) and | (or) operators  

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [109]:
a=np.arange(1,31).reshape(6,5)
print(a)

print("\n")

print(a[[0,1,2,3],[1,2,3,4]])


print("\n")

print(a[[0,4,5],3:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


[ 2  8 14 20]


[[ 4  5]
 [24 25]
 [29 30]]


In [112]:
# Create an empty array with 5 elements(from the memory)
print(np.empty((5,)))

[0.0e+000 4.9e-324 9.9e-324 1.5e-323 2.0e-323]


In [113]:
A = np.arange(10, 30, 5) #the same as range function(start , end+1 , step)
A

array([10, 15, 20, 25])

In [114]:
r = np.arange(10)  #(0,10,1)
print(r)

[0 1 2 3 4 5 6 7 8 9]


In [115]:
B = np.arange(0, 2, 0.3)
B

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

It is generally not possible to predict the number of elements obtained
It is usually better to use the function "linspace" that receives as an argument the number of elements that we want, instead of the step.It creates an array with values that are spaced linearly in a specified interval:


start → first number

stop → last number

num → how many values to generate (default = 50)

In [116]:
x= np.linspace(0, 2, num=9) #(start, end , number of elements)
print(x)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [117]:
w = np.linspace(10, 50, 5)
print(w)

[10. 20. 30. 40. 50.]


In [ ]:
np.linspace(10 ,30) #number of elements = 50 


In [118]:
np.arange(1,30,-1)

array([], dtype=int64)

In [ ]:
np.arange(30,2,-1)

The key difference is the **starting point, stopping point, and step sign**.

---

### 1️⃣ `np.arange(1, 30, -1)`

* Start: `1`
* Stop: `30`
* Step: `-1` (negative step means counting **down**)
* Problem: You’re trying to **count down** starting from `1` toward `30`.
  But `1` is already **less than** `30`, so NumPy can’t take even the **first step** — result is an **empty array** `[]`.

---

### 2️⃣ `np.arange(30, 2, -1)`

* Start: `30`
* Stop: `2`
* Step: `-1`
* Works fine: starts at `30`, subtracts `1` each step, stops *before* `2`.

Example:

```python
import numpy as np
print(np.arange(30, 2, -1))
```

Output:

```
[30 29 28 ... 5 4 3]
```

---

### 📏 Rule of thumb:

* If **step > 0**, then `start < stop` (count up)
* If **step < 0**, then `start > stop` (count down)

If you break that rule (like `np.arange(1, 30, -1)`), you get an empty array.

---

If you want, I can show you **a visual timeline** of how NumPy fills values for positive and negative steps — it makes this 100% clear in one picture.
