In [5]:
import numpy as np

# Basics

In [6]:
# we can declare a numpy array
a = np.array([1, 2, 3, 4, 5]) 
a


array([1, 2, 3, 4, 5])

In [7]:
# we can declare a numpy array
a = np.array([1, 2, 3, 4, 5]) 
print(a)


[1 2 3 4 5]


In [8]:
b= np.array([[6, 7, 8, 9, 10],[11, 12, 13, 14, 15]])
# here we made a 2D array where we have shape(2,5) , in math this is a matrix with 2 rows and 5 columns
print(b)
# look, In NumPy, a “matrix” is just a special case of an ndarray with 2 dimensions.

[[ 6  7  8  9 10]
 [11 12 13 14 15]]


In [9]:
# to get the dimensions of the array
b.ndim

2

In [10]:
# to get the shape of the array
b.shape
# it tells you the number of rows and columns in the array
# in this case, it is (2, 5) which means 2 rows and 5 columns

(2, 5)

In [11]:
 # to get the data type of the array
f = np.array([1.5, 2.5, 3.5, 4.5, 5.5])
print(a.dtype)
print(f.dtype)
# it tells you the data type of the elements in the array
# in this case, it is int64 which means the elements are 64-bit integers

int64
float64


In [12]:
#if do you eant to have a specific data type, you can specify it when creating the array
g = np.array([1, 2, 3, 4, 5], dtype=np.float32)
print(g.dtype)
g
# here we specified the data type as float32, which means the elements are 32-bit floating-point numbers

float32


array([1., 2., 3., 4., 5.], dtype=float32)

In [13]:
# also when we are not taking large numbers, we can use int8, int16, int32, int64
# and for floating point numbers, we can use float16, float32, float64
# these are the most common data types used in NumPy arrays

c= np.array([1, 2, 3, 4, 5], dtype=np.int16)
print(c.dtype)
# here we specified the data type as int8, which means the elements are 8-bit integers
# this is useful when we want to save memory and we know that the values will not exceed the range of int8

int16


In [14]:
# get size of the array
print(c.size)
# it tells you the number of elements in the array
# in this case, it is 5 which means there are 5 elements in the array

# is we want to get the size of the array in bytes
c.itemsize
# it tells you the size of each element in the array in bytes
# in this case, it is 1 which means each element is 2 byte

# to get whole size of the array in bytes
c.nbytes # equal to c.size * c.itemsize
# it tells you the total size of the array in bytes
# in this case, it is 10 which means the array takes 10 bytes of memory

5


10

In [15]:
# to be clear 

#numpy arrays are homogeneous, meaning all elements must be of the same data type.
# so for example, you cannot have a numpy array with both integers and strings.

s = np.array([1, 2, 3, 4.5 , 5])
# this will create an array with all elements as strings, because numpy will convert the integers to float to make them homogeneous
print(s)
# it will print ['1' '2' '3' '4' '5'] which means all elements are strings

x= np.array([1, 2, 3, 4.5 , '5'])
print(x)


[1.  2.  3.  4.5 5. ]
['1' '2' '3' '4.5' '5']


In [16]:
#we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray
mo=[1, 2, 3, 4.5 , '5']
a1= np.array(mo)
print(a1)
# it will print [1 2 3 4.5 '5'] which means all elements are strings

['1' '2' '3' '4.5' '5']


# Accessing/Changing specific elemts , row , colums ,etc

In [17]:
a = np.array([[1, 2, 3, 4, 5] ,[6, 7, 8, 9, 10]])
print(a)
a.shape

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


(2, 5)

In [18]:
# get specific element , we are using indexing (row, column)
print(a[0, 0])
# we can use negative indexing to get the last element
print(a[0, -1])



1
5


In [19]:
# get specific row

a[0]

array([1, 2, 3, 4, 5])

In [20]:
 # to get specific column, we can use slicing
print(a[:, 1])

[2 7]


In [21]:
# to get more fancy [startinging, ending, step] , it is like i want to get betwwen 2 and 6 but 

a[0,1 : 6:2]

#[in row,starting, ending, step]
# this will give us the elements in the first row starting from index 1 to index 6 with a step of 2
# so it will give us [2, 4]
# we can also use negative indexing to get the last element
# for example, a[0, -1] will give us the last element in the first row

array([2, 4])

In [22]:
# we change using index too 

a[1,0]= 100
print(a)
# this will change the element in the second row and first column to 100
# so the array will be [[1, 2, 3, 4, 5], [100, 7, 8, 9, 10]]

# we can do the same for series of numbers

a[:,2] = 20

a

[[  1   2   3   4   5]
 [100   7   8   9  10]]


array([[  1,   2,  20,   4,   5],
       [100,   7,  20,   9,  10]])

In [35]:
# 3D example 

d= np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
# to have a specific element in a 3D array, we can use indexing like this
print(d[0, 1, 0])  # This will give us the element at the first block, second row, first column
# it will print 3

# we are not deaing with matrices here, we are dealing with 3D shapes 
# so we can have 3D arrays with more than 2 dimensions

3


In [ ]:
#replace 
d[:,1,:] = [[8, 9], [10, 11]]
print(d) 
# this will replace the second row of each block with the new values
# so the array will be [[[1, 2], [8, 9]], [[5, 6], [10, 11]]]
# you can not do shomething like this : d[:,1,:] = [[8, 9,10], [10, 11]] 
# it will raise an error because the shape of the array will not match
# so you have to make sure that the shape of the array matches the shape of the values you are trying to assign

[[[ 1  2]
  [ 8  9]]

 [[ 5  6]
  [10 11]]]


In [39]:
t= np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]] , [[1,2,3,4], [5,6,7,8]]])
t

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]]])

# initialize different types of arrays 

In [ ]:
# all zeroes matrix
z= np.zeros((3, 4))  # 3 rows and 4 columns
# this will create a 2D array with 3 rows and 4 columns filled with zeros

print(z)

# toy can use in in all shapes, like 3D, 4D, etc.
l=np.zeros((2, 3, 4,5))  # 2 blocks, 3 rows and 4 columns
# this will create a 3D array with 2 blocks, each block has 3 rows and 4 columns filled with zeros

#Breaking down the shape (2, 3, 4, 5):
#1st dim = 2 → number of “big blocks” (think of it like 2 cubes)

#2nd dim = 3 → each block has 3 layers

#3rd dim = 4 → each layer has 4 rows

#4th dim = 5 → each row has 5 columns

#So the total number of elements = 2 × 3 × 4 × 5 = 120 zeros.

l

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [52]:
# all ones matrix
o= np.ones((3, 4))  # 3 rows and 4 columns
# this will create a 2D array with 3 rows and 4 columns filled with ones
print(o)

# you can also specify the data type when creating the array
o_float = np.ones((3, 4), dtype=np.int8)
o_float

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [53]:
# any other array can be created using the same method
# for example, you can create an array of random numbers, or an array of a specific value
# you can use np.full() to create an array filled with a specific value
full_array = np.full((2, 3), 7)  # 2 rows and 3 columns filled with 7
print(full_array)

[[7 7 7]
 [7 7 7]]


In [58]:
# fill_like 
# if i want to modify an existing array to have same num 
np.full(l.shape, 5)  # this will create an array with the same shape as l filled with 5
# so if l is a 3D array with shape (2, 3, 4, 5), it will create an array with the same shape filled with 5
# this is useful when you want to create an array with the same shape as another array but with different values
np.full_like(t, 5)


array([[[5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5]]])

In [69]:
# random decimal numbers
np.random.rand(2, 3)  # 2 rows and 3 columns filled with random numbers between 0 and 1
# this will create a 2D array with 2 rows and 3 columns filled with random numbers between 0 and 1
# you can also specify the data type when creating the array

np.random.random_sample(t.shape)

array([[[0.81343033, 0.28673982, 0.50024126, 0.00820028],
        [0.74075828, 0.36082545, 0.38561784, 0.48806911]],

       [[0.17920058, 0.02907709, 0.11688076, 0.61702026],
        [0.62618351, 0.4739087 , 0.6357372 , 0.63557092]],

       [[0.69944421, 0.96993602, 0.14105882, 0.70412027],
        [0.72621206, 0.71083507, 0.06063421, 0.27887625]]])

In [ ]:
# random integers
np.random.randint(4,10, size=(2, 3)) # random nymbers between 4 and 10, with shape (2, 3)
# this will create a 2D array with 2 rows and 3 columns filled with random integers between 4 and 10
# you can also specify the data type when creating the array



array([[7, 8, 9],
       [6, 9, 9]], dtype=int32)

In [84]:
# we can also make identity matrix 
np.identity(3)  # 3x3 identity matrix
# this will create a 2D array with 3 rows and 3 columns filled with ones on the diagonal and zeros elsewhere
# it is useful in linear algebra and matrix operations
# you can also specify the data type when creating the array


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [89]:
# to repeat an array 
y=np.array([1, 2, 3])
# to repeat the array 3 times
np.repeat(t,3 , axis=1) 

array([[[ 1,  2,  3,  4],
        [ 1,  2,  3,  4],
        [ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 5,  6,  7,  8],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [ 9, 10, 11, 12],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [13, 14, 15, 16],
        [13, 14, 15, 16]],

       [[ 1,  2,  3,  4],
        [ 1,  2,  3,  4],
        [ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 5,  6,  7,  8],
        [ 5,  6,  7,  8]]])

In [103]:
mat= np.ones((5, 5))  
mat[1:4,1:4]=0
mat[2,2]=9

print(mat)


#Also 

out= np.ones((5, 5))  
z=np.zeros((3, 3))
z[1,1]=9
print(z)
out[1:4,1:4]=z
print(out)

print(mat==out)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


Beeee careful when copies an array!!!!!!!!!!!!!!!

In [106]:
a=np.array([1, 2, 3, 4, 5])
# Beeee careful when copies an array!!!!!!!!!!!!!!!
b=a
b[0]=100
print(a)

# that is becuase that two arrays are pointing to the same memory location
# so if you change one, the other will change too
# if you want to create a copy of the array, you can use the copy() method

b = a.copy()
b[0] = 200
print(a)
print(b)

[100   2   3   4   5]
[100   2   3   4   5]
[200   2   3   4   5]


# Mathematcial operations

- one of the big uses of NumPy is all the mathematical cabilities that it offer

In [109]:
a=np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [ ]:
a+2


# we add 2 to all elements in the array
# it will return a new array with the same shape as the original array but with all elements increased by 2
# so it will return [3, 4, 5, 6, 7]

array([3, 4, 5, 6, 7])

In [112]:
print(a-2 )
# this will subtract 2 from all elements in the array
# look here that all those opwerations doesn't change the original array'ArithmeticError
print(a)

[-1  0  1  2  3]
[1 2 3 4 5]


In [ ]:
print(a*2)
print(a/2)


[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]


In [115]:
#but when will you change the original array? when use assiment operators like +=, -=, *=, /=, etc.
a += 2
print(a)
# this will add 2 to all elements in the array and change the original array
# so it will return [3, 4, 5, 6, 7]

[3 4 5 6 7]


In [118]:
print(a)
print(a+2)
print(a)

[3 4 5 6 7]
[5 6 7 8 9]
[3 4 5 6 7]


In [119]:
# you can also 
b= np.array([1, 2, 3, 4, 5])
a+b

array([ 4,  6,  8, 10, 12])

In [120]:
a**2

array([ 9, 16, 25, 36, 49])

In [123]:
# take sin 
print (np.sin(a))
# this will take the sine of all elements in the array
# it will return a new array with the same shape as the original array but with all elements replaced by their sine values
# so it will return [0.14112001, 0.90929743, 0.14112001, -0.7568025 , -0.95892427]
print(a)

[ 0.14112001 -0.7568025  -0.95892427 -0.2794155   0.6569866 ]
[3 4 5 6 7]


# Linear Algebra stuff